lib.name = c-siren~

class.sources = src/c-siren~.cpp
common.sources = src/CSirenEngine.cpp src/Sirene.cpp

PDLIBBUILDER_DIR = ./pd-lib-builder

cflags += -Isrc
cxxflags += -std=c++17

include $(PDLIBBUILDER_DIR)/Makefile.pdlibbuilder
